In [1]:
import pandas as pd

In [2]:
df_ECO = pd.read_excel('../teis-tacaelest/Data/NSS_ECO Data Ind 3 FFY 2023-24 20241211.xlsx' , sheet_name='ECO with Exit23-24 ')
df_ECO

,DISTRICT,CHILD_ID,Child ID_ Assessement point,ECO_Entry_DATE,Ent SOCIAL_SCALE,Ent KNOWLEDGE_SCALE,Ent APPROPRIATE_ACTION_SCALE,ECO_Exit_DATE,Exit SOCIAL_SCALE,Exit KNOWLEDGE_SCALE,...,BDI-2\nEntry SOCIAL_SCALE,BDI-2\nEntry KNOWLEDGE_SCALE,BDI-2\nEntry APPROPRIATE_ACTION_SCALE,BDI2 Entrance S/E\nStd Dev (Zscore),BDI2 Entrance\nCommunication Std Dev. (Z Score),BDI2 Entrance\nCognition Std Dev. (Z Score),BDI2 Entrance\nK/S\nStd Dev (Zscore),BDI2 Entrance\nAdaptive Std Dev (Zscore),BDI2 Entrance\nMotor Std Dev (Zscore),BDI2 Entrance\nA/B\nStd Dev (Zscore)
0,GN,473991,NaN,2020-01-07,1.0,1.0,1.0,2022-12-27,7.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GN,474186,NaN,2020-02-13,1.0,1.0,1.0,2023-10-26,7.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ET,474575,NaN,2020-01-17,3.0,5.0,4.0,2020-07-29,3.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NW,474623,NaN,2019-01-22,3.0,1.0,2.0,2022-12-16,4.0,4.0,...,3.0,6.0,2.0,-1.8,-1.27,-1.33,-1.300,-2.67,-1.67,-2.17
4,SW,474848,NaN,2021-07-09,3.0,3.0,6.0,2023-08-04,7.0,7.0,...,3.0,1.0,6.0,-2.0,-3.00,-2.47,-2.735,-1.67,-0.67,-1.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,SC,579717,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9995,SC,579729,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,ET,580243,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,FT,580375,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,MD,580840,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_bdi3 = pd.read_excel('../teis-tacaelest/Data/NSS data_BDI3 Scores 20230101 20240630_Compiled_20241107.xlsx')
df_bdi3.head()

,Last Name,First Name,Gender,Date of Birth,Location - Root Level (PC),Location - Root Level (AH),Location - Sub Level 1,Location - Sub Level 2,Location - Sub Level 3,Child ID,...,Cognitive-Perception and Concepts RS,Cognitive-Perception and Concepts SS,Cognitive-Perception and Concepts PR,Cognitive-Perception and Concepts AE,Cognitive-Perception and Concepts RDI,Cognitive-Perception and Concepts CSS,Cognitive-Perception and Concepts CSS 90%,Cognitive-Perception and Concepts Z-Score,Cognitive-Perception and Concepts T-Score,Cognitive-Perception and Concepts NCE
0,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Greater Nashville,NaN,NaN,474074,...,13.0,4.0,2,25,1990-01-01 00:00:00,464.0,450 - 479,2.00,30.0,8
1,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Greater Nashville,NaN,NaN,474186,...,24.0,8.0,25,40,68/90,510.0,502 - 517,0.67,43.0,36
2,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Upper Cumberland,NaN,NaN,474641,...,26.0,9.0,37,42,77/90,514.0,507 - 522,0.33,47.0,43
3,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Southwest,NaN,NaN,474848,...,17.0,6.0,9,32,25/90,487.0,476 - 497,1.33,37.0,22
4,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,South Central,NaN,NaN,474967,...,12.0,3.0,1,22,1990-01-01 00:00:00,451.0,429 - 473,2.33,27.0,1

In [4]:
df_bdi2 = pd.read_csv('../teis-tacaelest/Data/NSS data_BDI2 scores_20200101-20230131_20241106.csv',low_memory=False)
df_bdi2.head()

,StudentID,studentAssessmentID,resultStudentDomainID,Student TEIDS ID,domainID,domainText,ScoreTypeID,ScoreTypeText,StaffExternalID,testDate,...,AESign,isSSRequired,stdDevScore1,stdDevScore2,stdDevScore3,NCESign,totalCSS,totalCSSMin,totalCSSMax,NormType
0,2224693,8625078,138104116,52101,7,Self-Care,2.0,ItemDetails,34775.0,2/25/2022,...,NaN,1.0,NaN,NaN,NaN,NaN,322.0,301.0,343.0,2
1,2224693,8625078,138104117,52101,10,Adult Interaction,2.0,ItemDetails,34775.0,2/25/2022,...,NaN,1.0,NaN,NaN,NaN,NaN,413.0,403.0,423.0,2
2,2224693,8625078,138104118,52101,12,Self-Concept and Social Role,2.0,ItemDetails,34775.0,2/25/2022,...,NaN,1.0,NaN,NaN,NaN,NaN,365.0,355.0,375.0,2
3,2224693,8625078,138104119,52101,14,Receptive Communication,2.0,ItemDetails,34775.0,2/25/2022,...,NaN,1.0,NaN,NaN,NaN,NaN,343.0,333.0,353.0,2
4,2224693,8625078,138104120,52101,15,Expressive Communication,2.0,ItemDetails,34775.0,2/25/2022,...,NaN,1.0,NaN,NaN,NaN,NaN,288.0,267.0,309.0,2

In [5]:
df_bdi2_basic = df_bdi2[['Student TEIDS ID','testDate','lastUpdateDate','DQScore']]
type(df_bdi2_basic)

pandas.core.frame.DataFrame

In [6]:
df_bdi2_swap = df_bdi2[['domainText','Student TEIDS ID','testDate','lastUpdateDate','rawScore','DQScore','ZScore']].transpose()
df_bdi2_swap

,0,1,2,3,4,5,6,7,8,9,...,325676,325677,325678,325679,325680,325681,325682,325683,325684,325685
domainText,Self-Care,Adult Interaction,Self-Concept and Social Role,Receptive Communication,Expressive Communication,Gross Motor,Fine Motor,Attention and Memory,Perception and Concepts,Adaptive,...,Perception and Concepts,Adaptive,Personal Responsibility,Personal-Social,Peer Interaction,Communication,Motor,Perceptual Motor,Cognitive,Reasoning and Academic Skills
Student TEIDS ID,52101,52101,52101,52101,52101,52101,52101,52101,52101,52101,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
testDate,2/25/2022,2/25/2022,2/25/2022,2/25/2022,2/25/2022,2/25/2022,2/25/2022,2/25/2022,2/25/2022,NaN,...,1/26/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lastUpdateDate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
rawScore,2.0,14.0,6.0,4.0,1.0,5.0,5.0,6.0,5.0,2.0,...,12.0,17.0,NaN,39.0,NaN,24.0,70.0,NaN,32.0,NaN
DQScore,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.0,...,NaN,60.0,NaN,83.0,NaN,56.0,88.0,NaN,80.0,NaN
ZScore,-1.33,1.67,0.33,-1.33,-2.0,-0.67,0.0,-0.33,0.0,-1.33,...,-0.33,-2.67,NaN,-1.13,NaN,-2.93,-0.8,NaN,-1.33,NaN

In [7]:
df_domain = df_bdi2[['rawScore', 'scaledScore', 'PRScore', 'ZScore', 'AEScore', 'TScore', 'NceScore']].transpose()
df_domain

,0,1,2,3,4,5,6,7,8,9,...,325676,325677,325678,325679,325680,325681,325682,325683,325684,325685
rawScore,2.00,14.00,6.00,4.00,1.0,5.00,5.0,6.00,5.0,2.00,...,12.00,17.00,NaN,39.00,NaN,24.00,70.0,NaN,32.00,NaN
scaledScore,6.00,15.00,11.00,6.00,4.0,8.00,10.0,9.00,10.0,6.00,...,9.00,2.00,NaN,13.00,NaN,3.00,15.0,NaN,14.00,NaN
PRScore,9.00,95.00,63.00,9.00,2.0,25.00,50.0,37.00,50.0,9.00,...,37.00,0.40,NaN,13.00,NaN,0.20,21.0,NaN,9.00,NaN
ZScore,-1.33,1.67,0.33,-1.33,-2.0,-0.67,0.0,-0.33,0.0,-1.33,...,-0.33,-2.67,NaN,-1.13,NaN,-2.93,-0.8,NaN,-1.33,NaN
AEScore,0.00,5.00,2.00,0.00,0.0,0.00,2.0,1.00,2.0,NaN,...,13.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TScore,37.00,67.00,53.00,37.00,30.0,43.00,50.0,47.00,50.0,37.00,...,47.00,23.00,NaN,39.00,NaN,21.00,42.0,NaN,37.00,NaN
NceScore,22.00,85.00,57.00,22.00,8.0,36.00,50.0,43.00,50.0,22.00,...,43.00,1.00,NaN,26.00,NaN,1.00,33.0,NaN,22.00,NaN

In [8]:
#domain/subdomain scores: RS, SS, PR, Z-Score, AE, RDI, CSS, CSS 90%, T-Score, NCE
# RS = 'rawScore'  SS = 'scaledScore' , PR = 'PRScore' , Z-Score = 'ZScore' , AE = 'AEScore' , T-Score = 'TScore' , NCE = 'NceScore'
# Not Found: RDI, CSS, CSS 90%, 
#RDI may not be available bc it could be solely available to BDI-3